name: test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: initialise node
        uses: actions/setup-node@v4
      
      - name: install dependencies
        run: npm install
      
      - name: run tests
        run: npm test
    
